export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUIRED = "HOME_VIDEOS_REQUIRED";

export const SELECTED_VIDEOS_SUCCESS = "SELECTED_VIDEOS_SUCCESS";
export const SELECTED_VIDEOS_FAIL = "SELECTED_VIDEOS_FAIL";
export const SELECTED_VIDEOS_REQUIRED = "SELECTED_VIDEOS_REQUIRED";

export const CHANNEL_DETAIL_SUCCESS = "CHANNEL_DETAIL_SUCCESS";
export const CHANNEL_DETAIL_FAIL = "CHANNEL_DETAIL_FAIL";
export const CHANNEL_DETAIL_REQUIRED = "CHANNEL_DETAIL_REQUIRED";

export const CHANNEL_SUBSCRIPTION_STATUS = "CHANNEL_SUBSCRIPTION_STATUS";

export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";
export const COMMENT_LIST_REQUIRED = "COMMENT_LIST_REQUIRED";

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";
export const RELATED_VIDEO_REQUIRED = "RELATED_VIDEO_REQUIRED";


export const SEARCHED_VIDEO_SUCCESS = "SEARCHED_VIDEO_SUCCESS";
export const SEARCHED_VIDEO_FAIL = "SEARCHED_VIDEO_FAIL";
export const SEARCHED_VIDEO_REQUIRED = "SEARCHED_VIDEO_REQUIRED";


export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAIL = "CHANNEL_VIDEOS_FAIL";
export const CHANNEL_VIDEOS_REQUIRED = "CHANNEL_VIDEOS_REQUIRED";
